/**
 * Metro City Definitions
 * Maps major metro areas to their constituent localities/sub-areas.
 * Used for broader search and filtering when a user selects a metro city.
 */

const METRO_CITIES = {
  hyderabad: [
    "Hyderabad", // The city itself
    "Jubilee Hills",
    "Banjara Hills",
    "Secunderabad",
    "Sainikpuri",
    "Gachibowli",
    "Hitech City",
    "Madhapur",
    "Kukatpally",
    "Kondapur",
    "Miyapur",
    "Begumpet",
    "Ameerpet",
    "Tarnaka",
    "Uppal",
    "LB Nagar",
    "Dilsukhnagar",
    "Mehdipatnam",
    "Tolichowki",
    "Manikonda",
    "Nallagandla",
    "Kompally",
    "Alwal",
    "Attapur",
    "Masab Tank",
    "Khairatabad",
    "Himayatnagar",
    "Abids",
    "Charminar",
    "Falaknuma",
    "Shamshabad",
    "Somajiguda",
    "Panjagutta",
    "Begum Bazar",
    "Koti",
    "Malakpet",
    "Santosh Nagar",
    "Chandrayangutta",
    "Barkas",
    "Amberpet",
    "Ramanthapur",
    "Boduppal",
    "Nagole",
    "Vanasthalipuram",
    "Hayathnagar",
    "Chanda Nagar",
    "Hafeezpet",
    "Bachupally",
    "Pragathi Nagar",
    "Nizampet",
    "Bowenpally",
    "Maredpally",
    "Trimulgherry",
    "Yapral",
    "Malkajgiri",
    "Neredmet",
    "AS Rao Nagar",
    "ECIL",
    "Kapra",
    "Dammaiguda",
    "Nagaram",
    "Keesara",
    "Ghatkesar",
    "Medchal",
    "Shamirpet",
    "Bolarum",
    "Hakimpet",
    "Thumkunta",
    "Alwal",
    "Suchitra",
    "Jedimetla",
    "Quthbullapur",
    "Baltonagar",
    "Moosapet",
    "Erragadda",
    "Sanath Nagar",
    "Balkampet",
    "SR Nagar",
    "Yousufguda",
    "Srinagar Colony",
    "Krishna Nagar",
    "Venkatagiri",
    "Shaikpet",
    "Film Nagar",
    "Nandagiri Hills",
    "Gayatri Hills",
    "Prashasan Nagar",
    "Raidurgam",
    "Khajaguda",
    "Nanakramguda",
    "Financial District",
    "Kokapet",
    "Gandipet",
    "Narsingi",
    "Puppalaguda",
    "Langar Houz",
    "Golconda",
    "Ibrahimpatnam",
    "Adibatla",
    "Tukkuguda",
    "Maheshwaram",
    "Rajendranagar",
    "Budvel",
    "Kismatpur",
    "Bandlaguda Jagir",
    "Sun City",
    "Moinabad",
    "Chevella",
    "Shankarpally",
    "Mokila"
  ],
  bangalore: [
    "Bangalore",
    "Bengaluru",
    "Koramangala",
    "Indiranagar",
    "Whitefield",
    "HSR Layout",
    "Jayanagar",
    "JP Nagar",
    "Electronic City",
    "Marathahalli",
    "Hebbal",
    "Yelahanka",
    "Banashankari",
    "BTM Layout",
    "Bellandur",
    "Sarjapur",
    "Bannerghatta",
    "Malleswaram",
    "Rajajinagar",
    "Basavanagudi",
    "Frazer Town",
    "Sadashivnagar",
    "Ulsoor",
    "Richmond Town",
    "Vasanth Nagar",
    "Domlur",
    "Old Airport Road",
    "Brookefield",
    "Kundalahalli",
    "Varthur",
    "Kadugodi",
    "Hoodi",
    "KR Puram",
    "Mahadevapura",
    "CV Raman Nagar",
    "Kaggadasapura",
    "Vignan Nagar",
    "Murugeshpalya",
    "Jeevan Bima Nagar",
    "Thippasandra",
    "Banaswadi",
    "Kalyan Nagar",
    "Kammanahalli",
    "Hennur",
    "Horamavu",
    "Ramamurthy Nagar",
    "Kasturi Nagar",
    "Lingarajapuram",
    "RT Nagar",
    "Ganga Nagar",
    "Sanjay Nagar",
    "New BEL Road",
    "Mathikere",
    "Yeshwanthpur",
    "Peenya",
    "Jalahalli",
    "Vidyaranyapura",
    "Sahakara Nagar",
    "Thanisandra",
    "Jakkur",
    "Bagalur",
    "Devanahalli",
    "Chikkajala",
    "Vijayanagar",
    "Nagarbhavi",
    "Chandra Layout",
    "Kengeri",
    "Rajarajeshwari Nagar",
    "Jnana Bharathi",
    "Nayandahalli",
    "Basaveshwara Nagar",
    "Mahalakshmi Layout",
    "Nandini Layout",
    "Kurubarahalli",
    "Shankarapura",
    "Chamrajpet",
    "Hanumanth Nagar",
    "Girinagar",
    "Padmanabhanagar",
    "Kumaraswamy Layout",
    "Uttarahalli",
    "Konankunte",
    "Kanakapura Road",
    "Arekere",
    "Hulimavu",
    "Begur",
    "Bommanahalli",
    "Hongasandra",
    "Singasandra",
    "Kudlu Gate",
    "Hosa Road",
    "Kasavanahalli",
    "Kaikondrahalli",
    "Doddakannelli",
    "Carmelaram",
    "Gunjur",
    "Panathur",
    "Munnekollal",
    "AECS Layout",
    "BEML Layout",
    "ITPL",
    "Hope Farm",
    "Seegehalli",
    "Kannamangala",
    "Budigere Cross"
  ]
};

/**
 * Get regex pattern for a metro city to match address fields
 * @param {string} city - City name (e.g., 'hyderabad')
 * @returns {RegExp} - Regex to match any locality in the city
 */
function getCityLocalityRegex(city) {
  const normalizedCity = city.toLowerCase();
  const localities = METRO_CITIES[normalizedCity];
  
  if (!localities) {
    // Fallback to just the city name if not defined
    return new RegExp(city, 'i');
  }

  // Escape special characters in locality names and join with OR (|)
  const pattern = localities
    .map(loc => loc.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    .join('|');
  
  return new RegExp(pattern, 'i');
}

module.exports = {
  METRO_CITIES,
  getCityLocalityRegex
};
